# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12 
    commands:
      - echo Install...
      - npm install -g typescript
      - npm install
  pre_build:
    commands:
      - echo Building backend...
      - cd backend/
      - tsc
      - echo Installing source NPM dependencies...
      - cd ../frontend/programmar
      - npm install
  build:
    commands:
      - echo Build...
      - npm run-script build
  post_build:
    commands:
      - echo Build completed on `date`
      - cd ../../
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - robots.txt
    - manifest.json
    - index.html
    - favicon.ico
    - asset-manifest.json
    - static/*
  base-directory: 'frontend/programmar/build'